import mongoose from "mongoose"

const orderSchema = new mongoose.Schema({
    userId : {
        type : mongoose.Schema.Types.ObjectId ,
        ref : 'User'
    },
    products: [{
        type : mongoose.Schema.Types.ObjectId ,
        ref : 'Product'
    }],
    orderNumber : {
        type : Number,
        autoGenerated : true,
        unique : true
    },
    totalAmount : {
        type : Number ,
        required : true
    },
    shippingAddress : {
        street : {
            type : String ,
            required : true 
        },
        city : {
            type : String ,
            required : true 
        },
        state : {
            type : String ,
            required : true 
        },
        zipcode : {
            type : String ,
            required : true 
        },
        country : {
            type : String ,
            required : true 
        }
    }
},{
    timestamps : true
})
const Order = mongoose.model('Order',orderSchema)
export default Order
